spring:
  profiles:
    active: local
---
spring:
  profiles: local
  name: local-dev-profile
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/electricstore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: electricstoreadmin
    password: 123
  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway script
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
---
spring:
  profiles: prod
  name: live-prod-profile